### ISSUE TITLE
Authentication Headers - Stripe

### ISSUE THREAD

**Issue by jsblair9** [alecritson/Placid-Statamic#1]
Trying to connect to the Stripe API using HTTP basic auth - and I would believe that using the headers array option would work just great. Connecting to the stripe API through cURL is super easy otherwise and only requires that you send the user flag with your API key. 

Here is my set up...  running local on MAMP Pro w/SSL cert 
#### placid.yaml

```
stripe:
    url: 'https://api.stripe.com/v1/customers/'
    headers:
        Authorization: Bearer API_testkey 
```
#### template-file.html

```
  {{ placid handle="stripe" }}
    {{ data }}
      <p>{{ description }} - {{ email }}</p>
    {{ /data }}
  {{ /placid }}
```

**Comment by alecritson** [comment]
There seems to be an issue with Stripe and the way the requests are sent. I'll try work on a possible workaround

**Comment by alecritson** [comment]
If you download the plugin and update placid, a workaround is to set the curl options explicitly like this:

```
stripe:
 url: https://api.stripe.com/v1/charges
 curl:
  auth: [YOUR_API_KEY,]     
```
