### ISSUE TITLE
Failing in cache logic

### ISSUE THREAD

**Issue by thinkingcap** [alecritson/Placid-Statamic#11]
PHP 7.1.10 OSX
Using the following placid.yaml
```
example:
  url: https://jsonplaceholder.typicode.com/users
  cache: 1
  refresh: 60
```

Template
```
{{ placid:request handle="example" }}
{{ /placid }}
```
Seems to fail somewhere in cache block when checking `$cached_response`
