### ISSUE TITLE
Combine handles with params

### ISSUE THREAD

**Issue by curtisblackwell** [alecritson/Placid-Statamic#2]
Using this with Stripe requires setting curl options as you outlined in #1. However, I need to pass a variable into the URL, so I need to be able use both a config handle and a parameter.

Is there a way to have plugin parameters override the config options?

Ex:

``` html
{{ placid handle="stripe_subscriptions" url="https://api.stripe.com/v1/customers/{stripe_customer_id}/subscriptions" }}
```

``` yaml
stripe_subscriptions:
  curl:
    auth: [API_KEY,]
```
