### ISSUE TITLE
XML & JSON

### ISSUE THREAD

**Issue by alehandrof** [alecritson/Placid-Statamic#3]
I'm trying to consume the following URL:

```
http://pub.sandbox.orcid.org/0000-0002-6657-1928/orcid-bio
```

This returns an XML file, which Placid doesn't seem to like.

According to the [ORCID docs](https://github.com/ORCID/ORCID-Source/tree/master/orcid-pub-web) it's possible to request the data in JSON:

```
curl -H "Accept: application/orcid+json" 'http://pub.sandbox.orcid.org/0000-0002-6657-1928/orcid-bio' -L -i
```

But I don't see how I to get Placid to make this request.

Clearly, I'm a doofus. Any help would be appreciated.

**Comment by alecritson** [comment]
Hey @alehandrof 

No worries, I managed to get this working using the following set up:

`_config/add-ons/placid.yaml`

``` yaml
orcid:
    url: http://pub.sandbox.orcid.org/0000-0002-6657-1928/orcid-bio
    headers:
        Accept: application/orcid+json
```

Then in my template

```
{{ placid handle="orcid" }}
    {{ message-version }}
{{ /placid }}
```

Which gave me the value `1.1` which is what appeared when I queried the API using paw. See if that works for you :)
